# Generated by Django 4.2.1 on 2023-05-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_progress',
        ),
    ]
